"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/types";

type QuestionSummary = { id: string; prompt: string; type: string; points: number };
type AssessmentSummary = { id: string; title: string; published: boolean; questions: QuestionSummary[] };
type State = "idle" | "saving" | "done" | "error";

export function AdminAssessmentBuilder({ locale, courseId, assessments }: { locale: Locale; courseId: string; assessments: AssessmentSummary[] }) {
  const ar = locale === "ar"; const router = useRouter(); const [state, setState] = useState<State>("idle");
  async function deleteAssessment(id: string) { if (!window.confirm(ar ? "هل تريد حذف هذا الاختبار؟" : "Supprimer ce quiz ?")) return; setState("saving"); const response = await fetch(`/api/admin/learning-assessments/${id}`, { method: "DELETE" }); setState(response.ok ? "done" : "error"); if (response.ok) router.refresh(); }
  async function deleteQuestion(assessmentId: string, questionId: string) { if (!window.confirm(ar ? "هل تريد حذف هذا السؤال؟" : "Supprimer cette question ?")) return; setState("saving"); const response = await fetch(`/api/admin/learning-assessments/${assessmentId}/questions/${questionId}`, { method: "DELETE" }); setState(response.ok ? "done" : "error"); if (response.ok) router.refresh(); }
  async function createAssessment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState("saving"); const data = new FormData(event.currentTarget);
    const response = await fetch("/api/admin/learning-assessments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({
      courseId, titleFr: String(data.get("titleFr")), titleAr: String(data.get("titleAr")), instructionsFr: String(data.get("instructionsFr")), instructionsAr: String(data.get("instructionsAr")), timeLimitSeconds: Number(data.get("timeLimitMinutes"))*60, passingScore: Number(data.get("passingScore")), maxAttempts: Number(data.get("maxAttempts")),
    }) });
    setState(response.ok ? "done" : "error"); if (response.ok) { event.currentTarget.reset(); router.refresh(); }
  }
  async function createQuestion(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState("saving"); const data = new FormData(event.currentTarget); const assessmentId = String(data.get("assessmentId")); const type = String(data.get("type"));
    const optionCount = type === "TRUE_FALSE" ? 2 : 4;
    const options = Array.from({ length: optionCount }, (_, index) => ({ textFr: String(data.get(`optionFr${index+1}`)), textAr: String(data.get(`optionAr${index+1}`)), position: index+1, isCorrect: type === "MULTIPLE_CHOICE" ? data.getAll("correct").includes(String(index+1)) : String(data.get("correctOne")) === String(index+1) }));
    const response = await fetch(`/api/admin/learning-assessments/${assessmentId}/questions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ promptFr: String(data.get("promptFr")), promptAr: String(data.get("promptAr")), type, position: Number(data.get("position")), points: Number(data.get("points")), options }) });
    setState(response.ok ? "done" : "error"); if (response.ok) { event.currentTarget.reset(); router.refresh(); }
  }
  async function publication(id: string, published: boolean) { setState("saving"); const response = await fetch(`/api/admin/learning-assessments/${id}/publication`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ published }) }); setState(response.ok ? "done" : "error"); if (response.ok) router.refresh(); }
  return <div className="admin-assessment-builder"><form className="admin-course-form" onSubmit={createAssessment}><h3>{ar ? "إنشاء اختبار" : "Créer un quiz"}</h3><div className="field-row"><label><span>Titre FR</span><input name="titleFr" required minLength={3}/></label><label><span>العنوان AR</span><input name="titleAr" dir="rtl" required minLength={3}/></label></div><div className="field-row"><label><span>Instructions FR</span><textarea name="instructionsFr"/></label><label><span>التعليمات AR</span><textarea name="instructionsAr" dir="rtl"/></label></div><div className="admin-inline-fields"><label><span>{ar?"المدة (دقائق)":"Durée (minutes)"}</span><input name="timeLimitMinutes" type="number" min="1" max="240" defaultValue="15" required/></label><label><span>{ar?"درجة النجاح":"Seuil de réussite (%)"}</span><input name="passingScore" type="number" min="0" max="100" defaultValue="70" required/></label><label><span>{ar?"المحاولات":"Tentatives"}</span><input name="maxAttempts" type="number" min="1" max="10" defaultValue="3" required/></label></div><button className="admin-primary-button" disabled={state==="saving"}>{ar?"إنشاء الاختبار":"Créer le quiz"}</button></form>
    {assessments.length ? <form className="admin-course-form admin-question-form" onSubmit={createQuestion}><h3>{ar?"إضافة سؤال":"Ajouter une question"}</h3><div className="field-row"><label><span>{ar?"الاختبار":"Quiz"}</span><select name="assessmentId" required>{assessments.filter((item)=>!item.published).map((item)=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label><span>{ar?"النوع":"Type"}</span><select name="type"><option value="SINGLE_CHOICE">Single choice</option><option value="MULTIPLE_CHOICE">Multiple choice</option><option value="TRUE_FALSE">True / False</option></select></label></div><div className="field-row"><label><span>Question FR</span><textarea name="promptFr" required/></label><label><span>السؤال AR</span><textarea name="promptAr" dir="rtl" required/></label></div><div className="admin-inline-fields"><label><span>{ar?"الترتيب":"Position"}</span><input name="position" type="number" min="1" max="1000" defaultValue="1" required/></label><label><span>{ar?"النقاط":"Points"}</span><input name="points" type="number" min="1" max="100" defaultValue="1" required/></label></div><fieldset><legend>{ar?"خيارات الإجابة":"Options de réponse"}</legend>{[1,2,3,4].map((index)=><div className="admin-option-row" key={index}><input name={`optionFr${index}`} aria-label={`Option ${index} FR`} placeholder={`Option ${index} FR`} required/><input name={`optionAr${index}`} aria-label={`Option ${index} AR`} placeholder={`الخيار ${index}`} dir="rtl" required/><label><input type="radio" name="correctOne" value={index} defaultChecked={index===1}/><span>{ar?"صحيحة":"Correcte"}</span></label><label><input type="checkbox" name="correct" value={index}/><span>{ar?"متعدد":"Multiple"}</span></label></div>)}</fieldset><button className="admin-primary-button" disabled={state==="saving"}>{ar?"إضافة السؤال":"Ajouter la question"}</button></form> : null}
    <div className="admin-assessment-list">{assessments.map((item)=><article key={item.id} className="admin-assessment-item"><header><div><strong>{item.title}</strong><small>{item.published?(ar?"منشور":"Publié"):(ar?"مسودة":"Brouillon")} · {item.questions.length} {ar?"أسئلة":"questions"}</small></div><div className="admin-row-actions"><button type="button" className="btn btn-ghost btn-sm" onClick={()=>publication(item.id,!item.published)}>{item.published?(ar?"إلغاء النشر":"Dépublier"):(ar?"نشر":"Publier")}</button><button type="button" className="btn btn-ghost btn-sm" onClick={()=>deleteAssessment(item.id)}>{ar?"حذف":"Supprimer"}</button></div></header>{item.questions.length?<ul className="admin-question-list">{item.questions.map((question)=><li key={question.id}><span>{question.prompt}</span><div className="admin-row-actions"><small>{question.points} pts</small>{!item.published?<button type="button" className="btn btn-ghost btn-sm" onClick={()=>deleteQuestion(item.id,question.id)}>{ar?"حذف":"Supprimer"}</button>:null}</div></li>)}</ul>:null}</article>)}</div>{state==="done"?<p role="status" className="success-inline">{ar?"تم الحفظ.":"Enregistré."}</p>:state==="error"?<p role="alert" className="form-error">{ar?"تعذر الحفظ. تحقق من الحقول.":"Enregistrement impossible. Vérifiez les champs."}</p>:null}</div>;
}
