"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/types";
import { AdminObjectUpload } from "./AdminObjectUpload";

type State = "idle" | "loading" | "done" | "error";

function useAdminSubmit(endpoint: string) {
  const router = useRouter();
  const [state, setState] = useState<State>("idle");
  async function send(payload: unknown, form?: HTMLFormElement) {
    setState("loading");
    const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    setState(response.ok ? "done" : "error");
    if (response.ok) { form?.reset(); router.refresh(); }
  }
  return { state, send };
}

function Feedback({ state, locale }: { state: State; locale: Locale }) {
  if (state === "done") return <small className="success-inline">{locale === "ar" ? "تم الحفظ ✓" : "Enregistré ✓"}</small>;
  if (state === "error") return <small className="form-error">{locale === "ar" ? "تعذر الحفظ." : "Enregistrement impossible."}</small>;
  return null;
}

export function AdminWebinarForm({ locale }: { locale: Locale }) {
  const { state, send } = useAdminSubmit("/api/admin/webinars"); const ar = locale === "ar";
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); await send({ slug:String(f.get("slug")),titleFr:String(f.get("titleFr")),titleAr:String(f.get("titleAr")),descriptionFr:String(f.get("descriptionFr")),descriptionAr:String(f.get("descriptionAr")),trainerName:String(f.get("trainerName")),startsAt:String(f.get("startsAt")),durationMinutes:Number(f.get("durationMinutes")),meetingUrl:String(f.get("meetingUrl")||"")||null,replayUrl:String(f.get("replayUrl")||"")||null,published:true }, form); }
  return <form className="admin-course-form" onSubmit={submit}><div className="field-row"><label><span>Slug</span><input name="slug" required pattern="[a-z0-9-]+"/></label><label><span>{ar?"المدرب":"Formateur"}</span><input name="trainerName" required/></label></div><div className="field-row"><label><span>Titre FR</span><input name="titleFr" required/></label><label><span>العنوان AR</span><input name="titleAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Description FR</span><textarea name="descriptionFr" required/></label><label><span>الوصف AR</span><textarea name="descriptionAr" dir="rtl" required/></label></div><div className="field-row"><label><span>{ar?"التاريخ والوقت":"Date et heure"}</span><input name="startsAt" type="datetime-local" required/></label><label><span>{ar?"المدة (دقائق)":"Durée (minutes)"}</span><input name="durationMinutes" type="number" min="15" defaultValue="60" required/></label></div><div className="field-row"><label><span>URL session (optionnel)</span><input name="meetingUrl" type="url" placeholder="https://..."/></label><label><span>URL replay (optionnel)</span><input name="replayUrl" placeholder="/demo/... ou https://..."/></label></div><button className="btn btn-primary" disabled={state==="loading"}>{ar?"إضافة الندوة":"Ajouter le webinaire"}</button><Feedback state={state} locale={locale}/></form>;
}

export function AdminAvsForm({ locale }: { locale: Locale }) {
  const { state, send } = useAdminSubmit("/api/admin/avs"); const ar=locale==="ar";
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await send({displayName:String(f.get("displayName")),cityFr:String(f.get("cityFr")),cityAr:String(f.get("cityAr")),specialtyFr:String(f.get("specialtyFr")),specialtyAr:String(f.get("specialtyAr")),availabilityFr:String(f.get("availabilityFr")),availabilityAr:String(f.get("availabilityAr")),bioFr:String(f.get("bioFr")||""),bioAr:String(f.get("bioAr")||""),certified:f.get("certified")==="on",visible:true,image:String(f.get("image")||"")||null},form)}
  return <form className="admin-course-form" onSubmit={submit}><label><span>{ar?"الاسم":"Nom affiché"}</span><input name="displayName" required/></label><div className="field-row"><label><span>Ville FR</span><input name="cityFr" required/></label><label><span>المدينة AR</span><input name="cityAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Spécialité FR</span><input name="specialtyFr" required/></label><label><span>التخصص AR</span><input name="specialtyAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Disponibilité FR</span><input name="availabilityFr" required/></label><label><span>التوفر AR</span><input name="availabilityAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Bio FR</span><textarea name="bioFr"/></label><label><span>السيرة AR</span><textarea name="bioAr" dir="rtl"/></label></div><div className="field-row"><label><span>Photo URL</span><input name="image" type="url"/></label><label className="checkbox-row"><input name="certified" type="checkbox"/><span>{ar?"معتمد من الأكاديمية":"Certifié par l’Académie"}</span></label></div><button className="btn btn-primary" disabled={state==="loading"}>{ar?"إضافة ملف AVS":"Ajouter le profil AVS"}</button><Feedback state={state} locale={locale}/></form>;
}

export function AdminNewsForm({ locale }: { locale: Locale }) {
  const { state, send }=useAdminSubmit("/api/admin/news"); const ar=locale==="ar";
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await send({slug:String(f.get("slug")),tagFr:String(f.get("tagFr")),tagAr:String(f.get("tagAr")),titleFr:String(f.get("titleFr")),titleAr:String(f.get("titleAr")),excerptFr:String(f.get("excerptFr")),excerptAr:String(f.get("excerptAr")),contentFr:String(f.get("contentFr")),contentAr:String(f.get("contentAr")),published:true},form)}
  return <form className="admin-course-form" onSubmit={submit}><div className="field-row"><label><span>Slug</span><input name="slug" required pattern="[a-z0-9-]+"/></label><label><span>Tag FR / AR</span><span className="inline-inputs"><input name="tagFr" required/><input name="tagAr" dir="rtl" required/></span></label></div><div className="field-row"><label><span>Titre FR</span><input name="titleFr" required/></label><label><span>العنوان AR</span><input name="titleAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Extrait FR</span><textarea name="excerptFr" required/></label><label><span>المقتطف AR</span><textarea name="excerptAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Contenu FR</span><textarea name="contentFr" required rows={5}/></label><label><span>المحتوى AR</span><textarea name="contentAr" dir="rtl" required rows={5}/></label></div><button className="btn btn-primary" disabled={state==="loading"}>{ar?"نشر الخبر":"Publier l’actualité"}</button><Feedback state={state} locale={locale}/></form>;
}


export function AdminModuleForm({ locale, courses }: { locale: Locale; courses: Array<{ id: string; title: string }> }) {
  const { state, send } = useAdminSubmit("/api/admin/modules"); const ar = locale === "ar";
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); await send({ courseId: String(f.get("courseId")), position: Number(f.get("position")), titleFr: String(f.get("titleFr")), titleAr: String(f.get("titleAr")), descriptionFr: String(f.get("descriptionFr") || ""), descriptionAr: String(f.get("descriptionAr") || "") }, form); }
  return <form className="admin-course-form" onSubmit={submit}><label><span>{ar ? "الدورة" : "Formation"}</span><select name="courseId" required defaultValue=""><option value="" disabled>{ar ? "اختر دورة" : "Choisir une formation"}</option>{courses.map(course => <option value={course.id} key={course.id}>{course.title}</option>)}</select></label><div className="field-row"><label><span>{ar ? "ترتيب الوحدة" : "Position du module"}</span><input name="position" type="number" min="1" required/></label><label><span>{ar ? "عنوان الوحدة بالفرنسية" : "Titre du module FR"}</span><input name="titleFr" required/></label></div><label><span>{ar ? "عنوان الوحدة بالعربية" : "Titre du module AR"}</span><input name="titleAr" dir="rtl" required/></label><div className="field-row"><label><span>Description FR</span><textarea name="descriptionFr"/></label><label><span>الوصف AR</span><textarea name="descriptionAr" dir="rtl"/></label></div><button className="btn btn-secondary" disabled={state === "loading"}>{ar ? "إضافة الوحدة" : "Ajouter le module"}</button><Feedback state={state} locale={locale}/></form>;
}

export function AdminLessonForm({ locale, courses, modules = [] }: { locale: Locale; courses: Array<{ id: string; title: string }>; modules?: Array<{ id: string; courseId: string; title: string }> }) {
  const { state, send } = useAdminSubmit("/api/admin/lessons"); const ar=locale==="ar";
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await send({courseId:String(f.get("courseId")),moduleId:String(f.get("moduleId")||"")||null,position:Number(f.get("position")),titleFr:String(f.get("titleFr")),titleAr:String(f.get("titleAr")),descriptionFr:String(f.get("descriptionFr")||""),descriptionAr:String(f.get("descriptionAr")||""),durationSeconds:Number(f.get("durationSeconds")),videoUrl:String(f.get("videoObjectKey")||f.get("videoUrl")||"")||null,documentUrl:String(f.get("documentObjectKey")||f.get("documentUrl")||"")||null,preview:f.get("preview")==="on"},form)}
  return <form className="admin-course-form" onSubmit={submit}><div className="field-row"><label><span>{ar?"الدورة":"Formation"}</span><select name="courseId" required defaultValue=""><option value="" disabled>{ar?"اختر دورة":"Choisir une formation"}</option>{courses.map(course=><option value={course.id} key={course.id}>{course.title}</option>)}</select></label><label><span>{ar?"الوحدة (اختياري)":"Module (optionnel)"}</span><select name="moduleId" defaultValue=""><option value="">{ar?"بدون وحدة":"Sans module"}</option>{modules.map(module=><option value={module.id} key={module.id}>{module.title}</option>)}</select></label></div><div className="field-row"><label><span>{ar?"الترتيب":"Position"}</span><input name="position" type="number" min="1" required/></label><label><span>{ar?"المدة بالثواني":"Durée (secondes)"}</span><input name="durationSeconds" type="number" min="0" defaultValue="300" required/></label></div><div className="field-row"><label><span>Titre FR</span><input name="titleFr" required/></label><label><span>العنوان AR</span><input name="titleAr" dir="rtl" required/></label></div><div className="field-row"><label><span>Description FR</span><textarea name="descriptionFr"/></label><label><span>الوصف AR</span><textarea name="descriptionAr" dir="rtl"/></label></div><div className="field-row"><label><span>Vidéo — chemin local (développement)</span><input name="videoUrl" placeholder="/demo/inclusion-intro.mp4"/></label><label><span>Document — chemin local (développement)</span><input name="documentUrl" placeholder="/demo/support.pdf"/></label></div><div className="field-row"><AdminObjectUpload locale={locale} name="videoObjectKey" category="course" accept="video/mp4" labelFr="Vidéo privée (production)" labelAr="فيديو خاص (الإنتاج)"/><AdminObjectUpload locale={locale} name="documentObjectKey" category="course" accept="application/pdf,text/vtt" labelFr="Document privé / sous-titres" labelAr="وثيقة خاصة / ترجمة"/></div><label className="checkbox-row"><input name="preview" type="checkbox"/><span>{ar?"معاينة عامة":"Leçon en aperçu public"}</span></label><button className="btn btn-primary" disabled={state==="loading"}>{ar?"إضافة الدرس":"Ajouter la leçon"}</button><Feedback state={state} locale={locale}/></form>;
}
