import { notFound } from "next/navigation";
import { formatDate, isLocale } from "@/lib/i18n";
import { PageHero } from "@/components/ui/PageHero";
import { Icon } from "@/components/ui/Icon";
import { WebinarRegisterButton } from "@/components/interactive/WebinarRegisterButton";
import { listPublishedWebinars } from "@/server/queries/catalog";

export const dynamic="force-dynamic";
export default async function WebinarsPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const ar=locale==="ar";const rows=await listPublishedWebinars();return <><PageHero eyebrow={ar?"ندوات مباشرة وإعادات":"Webinaires & replays"} title={ar?"تعلّم مباشرة واحتفظ بإمكانية الرجوع":"Apprendre en direct, échanger, revoir"} description={ar?"جلسات مع مختصين وتسجيل مرتبط بحسابك وإعادات للمشاركين.":"Des sessions avec des spécialistes, une inscription liée à votre compte et des replays pour les participants."}/><section className="section"><div className="container webinar-page-grid"><div className="webinar-list-large">{rows.map(webinar=>{const replay=Boolean(webinar.replayUrl);return <article className="webinar-large-card premium-card" key={webinar.id}><div className="webinar-date-block"><strong>{webinar.startsAt.getDate()}</strong><span>{new Intl.DateTimeFormat(ar?"ar-TN":"fr-FR",{month:"short"}).format(webinar.startsAt)}</span></div><div className="webinar-large-main"><span className={replay?"status-pill replay":"status-pill"}>{replay?(ar?"إعادة":"Replay"):(ar?"قادم":"À venir")}</span><h2>{ar?webinar.titleAr:webinar.titleFr}</h2><p>{ar?webinar.descriptionAr:webinar.descriptionFr}</p><div className="meta-row"><span><Icon name="calendar" size={16}/>{formatDate(webinar.startsAt,locale)}</span><span><Icon name="clock" size={16}/>{new Intl.DateTimeFormat(ar?"ar-TN":"fr-FR",{hour:"2-digit",minute:"2-digit"}).format(webinar.startsAt)}</span><span><Icon name="user" size={16}/>{webinar.trainerName}</span></div></div><WebinarRegisterButton webinarId={webinar.id} locale={locale} replayUrl={webinar.replayUrl}/></article>})}</div><aside className="calendar-card premium-card"><span className="eyebrow">{ar?"المواعيد":"Agenda"}</span><h3>{ar?"جلسات الأكاديمية":"Les rendez-vous ANEI"}</h3><p>{ar?"بعد التسجيل ستظهر الندوة تلقائيًا في مساحتك الشخصية.":"Après inscription, la session apparaît automatiquement dans votre espace personnel."}</p><div className="mini-event-list">{rows.slice(0,4).map(w=><div key={w.id}><span>{w.startsAt.getDate()}</span><div><strong>{ar?w.titleAr:w.titleFr}</strong><small>{formatDate(w.startsAt,locale)}</small></div></div>)}</div></aside></div></section></>}
